---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  name: grafana-smtp-secret
  namespace: diagnostic
spec:
  encryptedData:
    password: AgA6TdejzdNmOLsw81Y/7eOWh/ApgIMCMDPmtaYmLqKMIW4hJIo+KIjdANdG6c8zxewqbzDsggTDsiGCosKERaXczFAQdKv+S+f1l48EbEQb9/NhdIKYeKIHxksX80hNCdnDn1/SDL5GtZcjapeoPxZtIBwOxM5m/zrOKhBXHJwbptprw6aHoWwF5i0h7IjJZhInJwN1SkONPBpnrwCJ+Xc8zQfO/MrvcDHZWo9SvzTHAykXFw2YqpD2H1HAqdlsCQndx5n1L+ufHT37g6Q4icCD1lR0fWzKujHesd74d49Ce9P0ISO/sxPq8MForSmrtZda4Jdg2JbIncOkHaqgkxMkjLbfdExjkz1YnPU45OwQwCn2M7Id7YpQAQVbDMGWkXDfAC41ok5vykVjGebLrjvrcJ60744+PpT+81lifow00kVviaAKjgsoSNtGe3FJQTWsyp6YbJOe3xbrqaZz4n3x/v1y5vI0w/WCbNKyhXwWjK5WByF6LV3PEpVOAaC+UeMnPPGES+IP6BKRWkS52L5Z22e3vaLXyyH8kEKQTgjBLTJi9u6awaGHa1w7xtmCZmthkBwDAbimUWBgrN1owDedduovTGJy0SBacOiODDPuHIlVr5tfDc+9hMjYxhB/9x3btdVi3d1bnk/ANlT5iFcYICTDu2jrm1YtMIkKrUwlCcwYu2r/uWvYZZZf6yDAsU2HNK8YgEfmGPKajc4y3QBg6vPM
    user: AgBQOy7Coys23gFe6gcqA4o9intkTKxbPsz8k7ik2LOO6j1+N0v3J/qGVOMo/TDtrrT3pFYYSwjL1Giymtyy2/S5EVsoXlheH222Npi7sXsXx2kUwaxY73A1Ehr7LVZKVKTny9pJ4ouxHGVtkJ1FO+jJR0pzeXEdacenK+9zsXFG0zzyD4Yej93BTL+MtbK1/852JfPrhM8bqjB9LVM5btvztROrYjdicUBTA3SGDKjTpyzbyNN+W6yOY/sbeNrCMX0mwRpYVO+asiJ9ME5s15CTQSqhreQBHQoy46x+EuTbjc8k6VHOmnhyoTABHK0SrDsQN13PfvLI11F0//qpv/5Mq2dGgG5+NmX1EzjpcNJCPV04cBCuFuEr1IJ0ntqKPm6KWr9fgIvHVF46xcJQS4G40ZvVnpb6RlWS3rbycSyE0yGb2OA/BYo2OEHB+pz3qubirwMUWl2YPXhlp3j4rlsBQQMDPsnE5bDW6hefj5UDdlVWoiX2w/4YK+BTzsqE+/BygU+avzb7yikgNAFGremoQdGOZj55bPnhLtzWpqlOACDLWSOiCxyt5sDYzpPD+Q3SocYWQRr4ZqDpkOJNoknH/nBs6hJKvusPRUrCX47AhtHeonw5WYH+180Qky0ExBcaGH3skSduFQEXOYLJ4aQqKDF8yfc43FA4mYEhZ7WIneS+OsRtFVnM2bMkkMfah7Qg3H45gVyoCLBA6CadCTrvqaUIOvQMUoXOCw==
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      name: grafana-smtp-secret
      namespace: diagnostic
