---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: tailscale-operator-secret
  namespace: tailscale
spec:
  encryptedData:
    client_id: AgAIMzprnNLLSlfbgU29N5MOcYvrwGpP5u0HkpHzqTgm64zHDqi7du+k/LrE2urrEcJfktijgDFBvA7emqVvm8TaFnoCrE5we3z7HgxahdG2Ai1MKnsKXUzyQ3v/7JyjPF54YmG/NrM13Ta0JweCs6i+URTLbZo0pisAdPMtWjTus4ADbuxO+Nc8esUuK3nkc2YPLQ+iL/OLjD8FCjURuP8dh6a9bH6lMal7uHccmSqI6cqtsXtjE+axc46A3PF7ScA29ZYVgB3qG6dFu8KmS2f0dx//1bRN53ioguNnbNrxuz3HOktY3ioZt4lJUNU1ZHSqU8MigXUGulthHCoFaJKC2xlr4bzhajQcTJhcQWHMVDC09fLrcg/0/EZGNX5il/RutUvZZR5oVopzv8QkXh8/KSxJNf3LB7JuqlAQxmKl8H3MiDKOXXqyUjgdXqxbel+uMXrvj+V87RCjVhvcEdUW4DZHiz3oDPjXJddCihKe48LZLI8aoYFBJe6jXUwBfbAI8gfTrHJCPUtQIJxsHt5u5A/BYlsK+LMI/rU1an4rBAUY3a+GXkHFtvkGN8AwUHvjB8RfUC4iudf8uMiDcXb8i/8Zf23GTmz1JOtVx9xMJ7XlJWmuEUK4tdiFxzoiuzQBlorkeyY+uF47XLee44rdcchBgg0eJFDxW72X3nCVxRgdkYhVd06U7RqTiVHdxgdDjnrq/JuGHWLE28/wur2gLg==
    client_secret: AgBk/ehrOyZDEUAX6uECsaWndFf8u6jW0A4+K7NkV3G9AqqOr/A7oLKED1I+E006uiAS9RCrgkQhbwNrAMr3BJfa1mIE0I+YEcOiFpGKB9vKs/DxR1byCfDhjMFClbnuAuLgwQE1f/bY8hijmOzOBsCUUkZ6M8o8Sg49RrVEUBFUYglnUsyrouaYkC+s/pA/bgNLjSTbDg9U2w883Kgx6ARocOjvIUEP+0pOzLN3LNKW8e/WoIrdy9RnWMavJbqBQGWCAGTA48vGpOABFiS2wvkQmrSkIB4URfycTVJblC8g4Ft3OcG9yUi+NiuhliHFr40GWuaddhcnzJjX+/W4u4itThNnKe9b1x1LJqdDdVPmB7g5v6k/xkLBVYoAtQvTVMLeyWFINsKgtEGQQduT9Xwng7jD2pG01Y9XyWIaotQRVzMggUelFEGM3+B4jvm5XWW+CdI8WKZUE4XZF1jDtd0/5TCe3q006+R/QfDGOUAstvMEQylyGvCIICWVbVer+g6ru+gC5HDROSAGmJZ9SkurHHt0venYQzzsSimpuHk1HFPtBuMIaL1pO6ocwJn+nWMpP4uzC59LCsy+f7u9mORu9hyCY/2caJ4ggIaATq6P9P86xHrboHxatRvKvJ/kmi7MG9C15siD0G6tIKc0lV1bdFDaH8O8H0PDmOSWA2kAvmWKz7SgobaRoP9LWXWw6KHuJ8NkoOLoRxUejTuQUMB9imS6R/XidYlfgekWWmd87F0G/3QqO26LNzbCEw0WVk2psLswmOfZpm8u9/gt5nFa
  template:
    metadata:
      name: tailscale-operator-secret
      namespace: tailscale
