---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: operator-oauth
  namespace: tailscale
spec:
  encryptedData:
    client_id: AgAyCsior8EMjmU0ryMYWXhi276ykQAE/Tie4XGjen2eggvfGuuKwE7jC/OcuJ0cL4CAcpgksVKNnDu5Fq2cd/Mf/lSr6M0x10gBxvYmaKCjnSY2qIUk9lyA6mQ2e2n6uDn/4gpBtC2zPULQU9wq6Idiy1XpGxxkCpjACzRbAxlY2pXphMeitJR7OjoITUrBE+Q67Thl2HDL0P+x6iuDh+z/4+w1i4+sIrvQ5OUd5rv9lgk3DvNVNdDB/2Ft2JZ0jQuaZtKAxGPlE+0vO0JBiSt8f7c0Qb1oyDmBf1mI92SjtwtSb9MjeDgwl7OQ3nAJ7V0CRVFuqaObbg+qORlarAkn1mI+S85z0lGONZ0Ju4k8Qnkm6ARGGUhMsYDiE0OVqpXnFFZTNY1oR3tKycpExwrO2htp76EdNBXo7PDKCY5JnIISnRBZmmznacpNUaknPDBc5gL+YXL5/yqsl7k/He1w6mI3KOXmJ9cNNyUfyP+ei/a3g+2w+EwdGwun5TKnZi3k3DZA0Y0kbkhvF4s3xGlTL+xk40I1T/cXkfkNrN5AoCdTEdqpRaAEcLZ+rF1oMxTX9PdhUFvnpe02vYrHZdqBpNI+ZHDoEEjwk9gE51aoKFGyvQztvFi5pgBrYBapKGdL3pE3N5lRnp/aNqo7urRuf9AqTU87XIvt0VA1usFMYnUL6monIHpsfIT2ughVIqYDOwzOKiiFFeCbtSSLfBdOSQ==
    client_secret: AgAu3GIIBa9aRo6P5lxzliYfuKzZSVkJ7Mn9PaWxhiBgWd92H9KNtsSWcjAESsw5t6hTlpOpeR81hdbzdhj1K7krwKz9MSXM332owPrYmYhUg7Tdy3eZrmaJfOOMxD2bAg1c3KscDFEO29LpF8+aJQ/xzNxXYfCKD4Y+FGWQiYrrSucwVf6sIzm7aypErPndcNqSHjNE0LG5A59T0Fcv2AG0nehD6eRg/jfUQEoufMw2O+MYA7s53ITlwnQxkcwthc11n/3fAMaX7cnFxe3w0aUPu2Hwy7YF8DZS+0bEmcZu4J+IYu2Nk9kMA3e59wU3FiRXrjoMQhTuord30oXr3VqYnjaP/AvMyjrRvOa8dpWSP9GvvMLcFcb8Ok3cvbaIEfuTAc2D2CTn+bTQnA7m/JFQrVHQ0yc3vWm44twnUVJw1Z16JGfz5ebpTwv2NqFa22Z+I/JlAxNqVntmrzxjndDAtCeRF1xdFwGgBtt4iKMf+1EV+bbsTeW0Sw66+83rdBPdUHJUSnOWbq9o3x+OW7OONefHzww62Rc4Pv6CLhLbQexyaB6b40cUNKkeCN9nTL1ZVK8RYbGa2+x3hvvBwbFpjtd4kinAm3rLXHtym6Y98cQijV+CUAnv3Mf5orEozrlKhWk+WpVlv5lF/x1K1KFm1Aa+qiYk8KtYPrOIm3VHtLIXsLWLQvCn5SFCDEwo9ebfxtNW2onoY87HmA/dzI1to5Uf1NUjkszdiG2dWMNSOGVxD4CotNGyWOXLXxedRXxCfJJ9nNlCHBUcf57OBDfa
  template:
    metadata:
      name: operator-oauth
      namespace: tailscale
