---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  name: tailscale-auth-secret
spec:
  encryptedData:
    TS_AUTHKEY: AgCZpUuxW0Dn2TVKLROJMMa+5LEnSJHcw9MR/k+wsZAa/CSwHmwD2FbXGeaTbEN/EEkn6Gath8uv1w30ZJ20AZApKNJ7EN5PshsnSOF0rYh2FKLqaFzr0nobryfDw8TdPKHmQFjmFVCJXL16L3YEJolJOQPC6L0027M0uwpfocGPiv4ofqTLsqygKNvJDNQ5Y2g3HtiYiuaniMpLd6LGUWA/2JFXArf4lpAN2gPrqWyShAm9Ic1p1fWiospW87rU6ORBEzWp6zMqlAKAgPyGJFIxz1E8PQCrHj+zwO8H9N9kIZA2An+AlXh7seS0e/GIUvKdhpUHpnCQPKX2c/vd//LAlkwOrG92uEP/4Y2ykoBnqDM/hQANbI/oGyV6LMXyZ8bVMvznfI2ZjShj4feYgo9SxEz1k+JLv1qTFGyOXDrtIzklC9mmMZxu7Q9HN9LOHkU4+H5xz2weHdbNlb7+9PoNV9PvBduBuv5YsOPFV7o0E2RqMkgJDP/7d+jM3xMPMsoHL14F1jyu0y5eIEBpjHpWdPQLjsXzjOdW8MpVT/gy9OJXI1eIWmVRLRInbg7k/VTFOPXckAFUEa/5p1M4Htkbv55CSB2pioibFlAJqQCWy8kXWxShAi4+4FYama++PsmUqQ2iALDKCsimsbdhACO2UD8b0E5La8LsMo7OX9ACrDyDKbQmQ1WOZw4d277+YVmQR6ylwCgOBgmlZ4/o3+qq3P+ZBqnYrC8HtZR7ThDh7I4MkDyfP8zjm5seulUGXDCst0iXYSVMPY9dSkY9vw==
  template:
    metadata:
      annotations:
        reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
        reflector.v1.k8s.emberstack.com/reflection-auto-enabled: "true"
        sealedsecrets.bitnami.com/cluster-wide: "true"
      name: tailscale-auth-secret
    type: Opaque
