---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  name: yamtrack-secret
spec:
  encryptedData:
    SECRET: AgCZroPUcpxhTpntir+iKwZuf89oGLNw0RtzOPu4bRPc12/hCUfmD/idWxElNfgukXSgTyKz9S2Iq/UTlHmF9QysYEfP+g90gnuF3fEO4FMigHKbXOqnPiv7jWt5cff4XxM+Tmvg+2h46+Bz1BXcw6pzZSQ8ZF5tvYz+qW/SIWYNyK+dsgI4hTY/YTPxB0fFAEXgMI/6qokjA5VdfyDTYaR503e6eRyo5T0LJ8K5lGRxuFoE9RnIwtB3QD4BT6CKPaA3l5Wdl7gTGxDfkx6d1Iu5xM4y+js8pcHo970DLM3voCJGQEkGgs0+d4QdUW7gpkbWGsVeNC1oHPcMIS2oFIRpvmewn4Gyo/DLlCZM0m2IeVxZzl6DM52AuTYmbYnIbZuar5Lwf1QvA3FutnYFfemNSrUMQdpphYldrrd1EMIeiG+Cb8qEowQi0Sj9uecvReF+XWX8gi8r730BQTBdIVeTC2A3DjQ1d1qJzIqTU9oh3S/oQCphC8z6erqorI7tFwafuLbmgKcb9QPtoojqisRyWRb+uQwgQ5guY10NhMj8h5hJaB0rdCdJmk3kKjYcW53B/RAKdAgCQz4dyXxtQNHnQSpQo+g7SAPvggsbaRQwkLkFNkX9hQjsuhYLgTMRv3tm0rnlCoDsavoko1VTFEMz3OFo1RU43JTlL6k+f3l6U/dvW4mIIOG5+cyckRkYooqCKwCBqdpIEPnoFcd+ITHm6h3EAywELW5HjDCYNOq0aQ==
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      name: yamtrack-secret
