---
garage:
  replicationFactor: 2
  s3:
    web:
      rootDomain: &rootDomain ".joeldollarhide.com"
    api:
      rootDomain: *rootDomain

deployment:
  replicaCount: 2

persistence:
  meta:
    storageClass: longhorn
    size: 100Mi
  data:
    storageClass: nfs
    size: 10Gi

monitoring:
  metrics:
    enabled: true
    serviceMonitor:
      enabled: true

ingress:
  s3:
    api:
      enabled: true
      className: traefik
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-prod
        traefik.ingress.kubernetes.io/router.middlewares: default-redirect-https@kubernetescrd
        traefik.ingress.kubernetes.io/preserve-host: "true"
      hosts:
        - host: &ingressHost s3-api.joeldollarhide.com
          paths:
            - path: /
              pathType: Prefix
      tls:
        - secretName: s3-api-tls
          hosts:
            - *ingressHost
    web:
      enabled: true
      className: traefik
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-prod
        traefik.ingress.kubernetes.io/router.middlewares: default-redirect-https@kubernetescrd
        traefik.ingress.kubernetes.io/preserve-host: "true"
        
        gethomepage.dev/enabled: "true"
        gethomepage.dev/name: "Garage"
        gethomepage.dev/type: "garage"
        gethomepage.dev/description: "S3 Api"
        gethomepage.dev/group: "homelab"
        gethomepage.dev/icon: "garage.png"
        gethomepage.dev/weight: "0"
      hosts:
        - host: &ingressHost s3-web.joeldollarhide.com
          paths:
            - path: /
              pathType: Prefix
      tls:
        - secretName: s3-web-tls
          hosts:
            - *ingressHost
