---
hull:
  objects:
    deployment:
      app:
        replicas: 1
        pod:
          containers:
            app:
              env:
                TYPE:
                  value: "FABRIC"
                EULA:
                  value: "TRUE"
                MEMORY:
                  value: "4G"
                TZ:
                  value: "America/New_York"
                USE_AIKAR_FLAGS:
                  value: "true"
                VERSION:
                  value: "1.21.11"
                DIFFICULTY:
                  value: "hard"
                VIEW_DISTANCE:
                  value: "16"
                MODE:
                  value: "survival"
                SERVER_NAME:
                  value: "Dollarcraft"
                ENABLE_WHITELIST:
                  value: "true"
                WHITELIST:
                  value: "ionizedwarhead"
                JVM_DD_OPTS:
                  value: "disable.watchdog:true"
                MAX_TICK_TIME:
                  value: "-1"
                ENABLE_AUTOPAUSE:
                  value: "true"
                VANILLATWEAKS_FILE:
                  value: "/config/vanillatweaks-datapacks.json,/config/vanillatweaks-craftingtweaks.json,"
                MODRINTH_MODPACK:
                  value: hermitcraft
                MODRINTH_PROJECTS:
                  value: |-
                    fabricproxy-lite
