---
garage:
  replicationFactor: 2

deployment:
  replicaCount: 4

persistence:
  meta:
    storageClass: longhorn
    size: 100Mi
  data:
    storageClass: nfs
    size: 10Gi

ingress:
  s3:
    api:
      enabled: true
      className: traefik
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-prod
        traefik.ingress.kubernetes.io/router.middlewares: default-redirect-https@kubernetescrd
        traefik.ingress.kubernetes.io/preserve-host: "true"
      hosts:
        - host: &ingressHost s3-api.joeldollarhide.com
          paths:
            - path: /
              pathType: Prefix
      tls:
        - secretName: s3-api-tls
          hosts:
            - *ingressHost
